title: OhMyBrew!
email: tyler.n.king@outlook.com
description: My beer, ramblings, & work.
baseurl: ~
url: https://ohmybrew.com
github_username:  ohmybrew
instagram_username: ohmybrew
markdown: kramdown
kramdown:
  input: GFM
paginate: 5
paginate_path: /page/:num/
permalink: /:year/:month/:day/:title
exclude: [vendor]
#include: [_pages]
gems:
  - jekyll-sitemap
  - jekyll-paginate
