title: Tyler King
email: tyler.n.king@gmail.com
description: My beer, ramblings, & work.
baseurl: ~
url: http://tylerking.me
github_username:  tyler-king
instagram_username: tylernking
markdown: kramdown
kramdown:
  input: GFM
paginate: 5
paginate_path: /page/:num/
permalink: /:year/:month/:day/:title
exclude: [vendor]
#include: [_pages]
gems:
  - jekyll-sitemap
  - jekyll-paginate
