FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  bash \
  coreutils \
  findutils \
  gawk \
  grep \
  lynx \
  pandoc \
  pcregrep \
  perl \
  sed \
  tidy \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
